@api = http://localhost:5072

### add product
Post {{api}}/product
Content-Type: application/json

{
    "name": "Spodenki"
} 

### get products
GET {{api}}/products
Content-Type: application/json

{
} 

### get product
GET {{api}}/product/B7306338-F29C-496A-AD57-E35C5BEEEA7E
Content-Type: application/json

{
} 